SELECT
    cc.CAR_ID,
    cc.CAR_TYPE,
    (cc.DAILY_FEE * 30 * (100 - cd.DISCOUNT_RATE) * 0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR cc
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN cd ON cc.CAR_TYPE = cd.CAR_TYPE
    AND cd.DURATION_TYPE = '30일 이상'
WHERE cc.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY cr
        WHERE cc.CAR_ID = cr.CAR_ID
            AND cr.START_DATE <= DATE '2022-11-30'
            AND cr.END_DATE >= DATE '2022-11-01')
    AND cc.DAILY_FEE * 30 * (100 - cd.DISCOUNT_RATE) * 0.01 >= 500000
    AND cc.DAILY_FEE * 30 * (100 - cd.DISCOUNT_RATE) * 0.01 <= 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC