SELECT
    i.FOOD_TYPE,
    i.REST_ID,
    i.REST_NAME,
    i.FAVORITES
FROM REST_INFO i
JOIN (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) c
ON i.FOOD_TYPE = c.FOOD_TYPE
AND i.FAVORITES = c.MAX_FAV
ORDER BY i.FOOD_TYPE DESC