SELECT
    m.MEMBER_NAME,
    r.REVIEW_TEXT,
    TO_CHAR(r.REVIEW_DATE, 'YYYY-MM-DD') AS review_date
FROM MEMBER_PROFILE m
JOIN REST_REVIEW r ON m.MEMBER_ID = r.MEMBER_ID
WHERE m.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(cnt)
        FROM (
            SELECT COUNT(*) AS cnt
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        )
    )
)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC